mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views


urlpatterns = [
	url(r'^polls/', include('polls.urls'),),
    url(r'^admin/', admin.site.urls),
    
    

]

polls/urls.py
from django.conf.urls import url
from . import views
app_name = 'polls'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    url(r'^users/$', views.users, name='users'),
    url(r'^(?P<user_id>[0-9]+)/answer/$', views.answer, name='answer'),

]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.conf import settings

User = settings.AUTH_USER_MODEL
# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')

	def __str__(self):
		return self.question_text

	def was_published_recently(self):
		now = timezone.now()
		return now - datetime.timedelta(days=1) <= self.pub_date <= now

class Choice(models.Model):
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)

	def __str__(self):
		return self.choice_text
		

class UserAnswer(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	question = models.ForeignKey(Question, on_delete=models.CASCADE)
	choice = models.ForeignKey(Choice, on_delete=models.CASCADE)	

	class Meta:
		unique_together = (('user', 'question'),)

	

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone


from django.contrib.auth import get_user_model
from django.db import IntegrityError
from .models import Choice, Question, UserAnswer, User



class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'

	def get_queryset(self):
		"""Return the last five published questions (not including
		those to be published in the future).
		"""
		return Question.objects.filter(
			pub_date__lte=timezone.now()).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'
	def get_quesryset(self):
		return Question.objects.filter(pub_date__lte=timezone.now())

class ResultsView(generic.DetailView):
	model = UserAnswer
	template_name = 'polls/results.html'

def vote(request, question_id):
	question = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = question.choice_set.get(pk=request.POST['choice'])
		UserAnswer.objects.create(user = request.user, 
			                      question=question, choice=selected_choice)
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question': question,
			'error_message': "You didn't select a choice.",
			})
	except IntegrityError as e:
			return render(request, 'polls/detail.html', {
				'question': question,
				'error_message': "Вы уже голосовали",
				})
	else:
		selected_choice.votes += 1
		selected_choice.save()

	return render(request, 'polls/results.html', {'question': question})

def users(request):
	User = get_user_model()
	users = User.objects.all()
	return render(request, 'polls/list_users.html', {'users': users})

def answer(request, user_id):
	user_answers = UserAnswer.objects.filter(user_id=user_id)
	return render(request, 'polls/list_answer.html', 
					{'user_answers': user_answers, })

mysite/templates/base.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<!-- link Bootstrap 3-->
	<link rel="stylesheet" 
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<header>
	<div class="col-xs-6">
		<h1> Голосование на разные темы </h1>
	</div>
	{% if user.is_authenticated %}
		<div class="col-xs-4" id="user-toolbar">
			<span>{{user.username }}</span>
			<a href="{% url 'users:auth_logout' %}">Выйти</a>
		</div>
		<!-- User toolbar for anonymous users -->
	{% else %}
		<div class="col-xs-6" id="user-toolbar">
			<a href="{% url 'users:auth_login' %}">Войти</a>  | 
			<a href="{% url 'users:registration_register' %}">Регистрация</a>
		</div>
	{% endif %}
</header>
<div class="col-xs-12">
	<div class="polls">
		{% if latest_question_list %}
			<ul>
			{% for question in latest_question_list %}
				<li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No polls are available.</p>
		{% endif %}
	</div>
	<div>
		
	</div>
</div>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif%}
<form action="{% url 'polls:vote' question.id %}" method="post">
	{% csrf_token %}
	{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{choice.choice_text}}</label><br>
	{% endfor %}
	<input type="submit" name="Vote">
</form>

polls/templates/polls/index.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<!-- link Bootstrap 3-->
	<link rel="stylesheet" 
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<div class="body">
	<div class="col-xs-6">
		<h1> Голосование на разные темы </h1>
	{% if user.is_authenticated %}
	  <p>Добро пожаловать, {{ user.username }}. Спасибо, что не забываете нас.</p>
	  <div class="col-xs-12">
		<div class="polls">
			{% if latest_question_list %}
				<ul>
				{% for question in latest_question_list %}
					<li><a href="{% url 'polls:detail' question.id %}">
										{{question.question_text}}</a></li>
				{% endfor %}
				</ul>
			{% else %}
				<p>No polls are available.</p>
			{% endif %}
		</div>
	</div>
	{% else %}
	  <div class="col-xs-12">
		<div class="polls">
			{% if latest_question_list %}
				<ul>
				{% for question in latest_question_list %}
					<li>{{question.question_text}}</li>
				{% endfor %}
				</ul>
			{% else %}
				<p>No polls are available.</p>
			{% endif %}
		</div>
	</div>
	{% endif %}
</div>

polls/templates/polls/list_answer.html
<div>
	<ul>{% for user_answer in user_answers %}
		<h1>{{user_answer.user}}</h1>
		<li>{{user_answer.choice}}</li>


		{% endfor %}
	</ul>
</div>

polls/templates/polls/list_users.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<!-- link Bootstrap 3-->
	<link rel="stylesheet" 
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<div>
	<div class="col-xs-6">
		<h1> Список пользователей </h1>
	</div>
	<table class="table table-striped">
		<thead>
			<tr>
				<td>E-mail</td>
				<td>User</td>
				<td>Дата регистрации</td>
				<td>Фамилия</td>
				<td>Имя</td>
			</tr>
		</thead>
		<tbody>
		{% for user in users %}
			<tr>
				<td>{{ user.email }}</td>
				<td><a href="{% url 'polls:answer' user.id %}">{{ user.username }}</a></td>
				<td>{{ user.data_joined }}</td>
				<td>{{ user.first_name }}</td>
				<td>{{ user.last_name }}</td>
			</tr>
		{% endfor %}
		</tbody>
	</table>
</div>

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote {{choice.votes|pluralize }}</li>
{% endfor %}
</ul>
<a href="{% url 'polls:index' %}">Назад к вопросам</a>

templates/base.html
{% load staticfiles %}
<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}">
<!-- link Bootstrap 3-->
	<link rel="stylesheet" 
          href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<div>
	<div class="col-xs-6">
		<h1> Здесь вы можете проголосовать </h1>
	</div>
	{% block content %}
	<div class="col-xs-12">
		<div class="polls">
		{% if latest_question_list %}
			<ul>
			{% for question in latest_question_list %}
				<li><a href="{% url 'polls:detail' question.id %}">{{question.question_text}}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<p>No polls are available.</p>
		{% endif %}
		</div>
	</div>
	{% endblock content%}
</div>